# ==================================================================================================
# 1.  EOF of geopotential height anomalies of 500 hPa
#     This requires two files: 1) monthly averaged surface pressure (ps), 2) monthly averaged geopotential height (zg)
#     the code is in NCL
# ==================================================================================================

settings:
  driver: EOF_500hPa.py
  long_name: EOF of geopotential height anomalies of 500 hPa

# USAGE varlist
# var_name      time-frequency     [requirement]
#
# - var_name: as found in var_code/util/set_variables_*
# - freq: mon (monthly), day, 6hr, 3hr, 1hr
# - requirement = blank  (default = optional)                                          
#                      required (package cannot run without this)                           
#                      required unless field_name field_name2 ...
# - alternates: 
#
#   nb. if a variable is required at multiple time frequencies,
#       list it separately for each one
#
#          Clearly the developer can just leave out optional files
#          However, it is always nice to get an upfront warning of missing files

varlist:
  - var_name: zg_var
    freq: mon
    requirement: required
  - var_name: ps_var
    freq: mon
    requirement: required