# Runtime yaml configuration file template for the MDTF-diagnostics package
# Create a copy of this file for personal use, and pass it to the framework
# with the -f | --configfile flag

# List of POD(s) to run
pod_list:
  - "example_multicase"
  - "MJO_suite"

# Case list entries (must be unique IDs for each simulation)
case_list:
  "CMIP_Synthetic_r1i1p1f1_gr1_19800101-19841231" :
    model: "test"
    convention: "CMIP"
    startdate: "19800101:000000"
    enddate: "19841231:000000"

  "CMIP_Synthetic_r1i1p1f1_gr1_19850101-19891231" :
    model: "test"
    convention: "CMIP"
    startdate: "19850101:000000"
    enddate: "19891231:000000"

### Data location settings ###
# Required: full path to ESM-intake catalog header file
DATA_CATALOG: "/local2/home/mdtf/MDTF-diagnostics/tools/catalog_builder/examples/gfdl/esm_catalog_DECK_ESM4_historical_D1_atmos_ts_monthly_5yr_subset.json"
# Optional: Parent directory containing observational data used by individual PODs.
# If defined, the framework assumes observational data is in OBS_DATA_ROOT/[POD_NAME]
OBS_DATA_ROOT: "../inputdata/obs_data"
# Required: Working directory location. Temporary files are written here.
# Final output is also written here if the OUTPUT_DIR is not defined.
WORK_DIR: "../wkdir"
# Optional: Location to write final output if you don't want it in the wkdir
OUTPUT_DIR: ""
### Environment Settings ###
# Required: Location of the Anaconda/miniconda installation to use for managing
# dependencies (path returned by running `conda info --base`.)
conda_root": ""
# Optional: Directory containing the framework-specific conda environments. This should
# be equal to the "--env_dir" flag passed to conda_env_setup.sh. If left
# blank, the framework will look for its environments in conda_root/envs
conda_env_root": ""
### Data type settings ###
# Method used to fetch model data.
data_manager: "Local_File"
# set to true to handle data files > 4 GB
large_file: False
### Output Settings ###
# Set to true to have PODs save postscript figures in addition to bitmaps.
save_ps: False
# Set to true to have PODs run on data that has already been processed
persist_data: False
# Set to true to save HTML and bitmap plots in a .tar file.
make_variab_tar: False
# Set to true to overwrite results in OUTPUT_DIR; otherwise results saved
# under a unique name.
overwrite: False
### Developer settings ###
# Set to True to run the preprocessor
run_pp: True
# Additional custom preprocessing scripts to run on data
# place these scripts in the sites/local directory
# The framework will run the specified scripts whether run_pp is set to True or False
user_pp_scripts:
  - ""