# ==================================================================================================
# 3.  Diurnal cycle of precipitation 
#     see Gervais et al., J. Climate, 5219-5239, 2014.
#     This requires 3 hourly precipitation. 
#     the code is in NCL
# ==================================================================================================

settings:
  driver: SM_ET_coupling.py
  long_name: Coupling between Soil Moisture and EvapoTranspiration 
  description: Coupling of Soil Moisture with Evapotranspiration 
  conda_env: R

#One filelist should be placed in each suite directory
#
# USAGE
# #optional comments need to begin with #
# # 2 or three fields:
# var_name      time-frequency     required [optional]
# 
# - var_name: as found in src/config_*.yml
# - time-frequency: mon (monthly), day, 6hr, 3hr, 1hr
#   nb. if a variable is required at multiple time frequencies,
#       list it separately for each one
# - required: 
#          True = the file is required to run the package
#                 (package will abort if file not found)
#          False = the file is optional (package continues regardless)
#          Clearly the developer can just leave out optional files
#          However, it is always nice to get an upfront warning of missing files

varlist:
  - var_name: mrsos_var
    freq: mon
    requirement: required
  - var_name: evspsbl_var
    freq: mon
    requirement: required
  - var_name: pr_var
    freq: mon
    requirement: required
